#spring:
 # datasource:
 #   url: jdbc:postgresql://localhost:5432/ejada
 #   username: postgres
 #   password: postgres
 # redis:
 #   host: redis
 #   port: 6379
#  kafka:
#    bootstrap-servers: http://localhost:29092
#  flyway:
 #   enabled: true
 #   locations: classpath:db/migration/common,classpath:db/migration/{vendor}
 # data:
 #   redis:
  #    repositories:
 #       enabled: false


