apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}-config
  labels:
{{ include "api-gateway.labels" . | nindent 4 }}
data:
  application.yml: |
{{- .Values.config.application | nindent 4 }}
  gateway.yml: |
{{- .Values.config.gateway | nindent 4 }}
  routes.yml: |
{{- .Values.config.routes | nindent 4 }}
  security.yml: |
{{- .Values.config.security | nindent 4 }}
  tenant.yml: |
{{- .Values.config.tenant | nindent 4 }}
  resilience.yml: |
{{- .Values.config.resilience | nindent 4 }}
  logging.yml: |
{{- .Values.config.logging | nindent 4 }}
