{{- range $name, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-%s" (include "api-gateway.fullname" $) $name) $secret.name }}
  labels:
{{ include "api-gateway.labels" $ | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
