spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

shared:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:${SHARED_KAFKA_BOOTSTRAP_SERVERS:http://localhost:29092}}
    env: ${APP_ENV:${SPRING_PROFILES_ACTIVE:dev}}
